import os
import asyncio
from datetime import datetime
from typing import List, Optional
from uuid import UUID
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from loguru import logger

from app.database.session import async_session_maker
from app.database.repositories.simulation_repository import SimulationRepository
from app.database.repositories.metrics_repository import MetricsRepository
from app.database.repositories.optimization_repository import OptimizationRepository
from app.database.models.simulation import Simulation
from app.database.models.metrics import SimulationMetric
from app.database.models.optimization import Optimization
from app.energyplus.config import DEFAULT_IDF_PATH, DEFAULT_EPW_PATH, OUTPUT_BASE_DIR
from app.energyplus.runner import EnergyPlusRunner
from app.energyplus.parser import EnergyPlusParser
from app.websocket.manager import ws_manager
from app.websocket.events import create_websocket_event
from app.core.custom_exceptions import DatabaseException, SimulationException

class SimulationService:
    def __init__(self, session: AsyncSession):
        self.session = session
        self.repository = SimulationRepository(session)
        self.metrics_repository = MetricsRepository(session)

    async def start_simulation(self, name: str) -> Simulation:
        """
        Creates a running simulation record in DB and triggers async runner in background.
        """
        logger.info(f"Triggering simulation start query: {name}")
        
        # Stop any currently active simulations
        try:
            query = select(Simulation).where(Simulation.status == "running")
            result = await self.session.execute(query)
            active_sims = list(result.scalars().all())
            for active_sim in active_sims:
                active_sim.status = "finished"
                await self.repository.update(active_sim)
                
            # Create new simulation
            sim = Simulation(simulation_name=name, status="running")
            created_sim = await self.repository.create(sim)
            
            # Spawn background execution thread task
            asyncio.create_task(self._run_simulation_in_background(created_sim.id))
            
            return created_sim
        except Exception as e:
            logger.error(f"Failed to start simulation: {e}")
            raise DatabaseException(f"Failed to start simulation process: {e}")

    async def get_simulation_status(self, simulation_id: UUID) -> Simulation:
        """
        Get simulation run profile details.
        """
        sim = await self.repository.get_by_id(simulation_id)
        if not sim:
            raise SimulationException(f"Simulation with ID {simulation_id} not found.")
        return sim

    async def get_simulation_results(self, simulation_id: UUID) -> List[SimulationMetric]:
        """
        Retrieve database metrics records generated by the run.
        """
        return await self.metrics_repository.get_by_simulation_id(simulation_id)

    async def get_latest_simulation(self) -> Optional[Simulation]:
        """
        Retrieve most recent simulation run records.
        """
        query = select(Simulation).order_by(Simulation.created_at.desc()).limit(1)
        result = await self.session.execute(query)
        return result.scalars().first()

    async def update_simulation_control(self, hvac_setpoint: float, lighting_dim: int) -> dict:
        """
        Updates parameter override configs (stub).
        """
        return {
            "status": "success",
            "applied": {
                "hvac_setpoint": hvac_setpoint,
                "lighting_dim": lighting_dim
            },
            "timestamp": datetime.utcnow().isoformat()
        }

    async def _run_simulation_in_background(self, sim_id: UUID):
        """
        Asynchronous background task runner.
        """
        logger.info(f"Starting background simulation runner for: {sim_id}")
        
        try:
            # 1. Update WebSocket starting
            start_event = create_websocket_event("SIMULATION_PROGRESS", {"progress": 10, "status": "starting"})
            await ws_manager.broadcast(start_event)
            
            output_dir = os.path.join(OUTPUT_BASE_DIR, str(sim_id))
            runner = EnergyPlusRunner(DEFAULT_IDF_PATH, DEFAULT_EPW_PATH, output_dir)
            
            # 2. Spawn simulation subprocess (or mock)
            run_event = create_websocket_event("SIMULATION_PROGRESS", {"progress": 30, "status": "running"})
            await ws_manager.broadcast(run_event)
            csv_path = await runner.run_simulation()
            
            # 3. Parse output CSV
            parse_event = create_websocket_event("SIMULATION_PROGRESS", {"progress": 70, "status": "parsing"})
            await ws_manager.broadcast(parse_event)
            parser = EnergyPlusParser(csv_path)
            metrics = parser.parse_metrics()
            
            # 4. Open fresh session connection to commit records in background thread context
            async with async_session_maker() as db_session:
                bg_sim_repo = SimulationRepository(db_session)
                bg_metrics_repo = MetricsRepository(db_session)
                bg_opt_repo = OptimizationRepository(db_session)
                
                # Fetch and finalize simulation status
                sim = await bg_sim_repo.get_by_id(sim_id)
                if sim:
                    sim.status = "finished"
                    sim.updated_at = datetime.utcnow()
                    await bg_sim_repo.update(sim)
                
                # Bulk insert parsed timesteps metrics
                for m_dict in metrics:
                    metric = SimulationMetric(
                        simulation_id=sim_id,
                        **m_dict
                    )
                    await bg_metrics_repo.create(metric)
                    
                # Create a baseline mock Optimization saving record
                opt = Optimization(
                    simulation_id=sim_id,
                    energy_before=150.0,
                    energy_after=120.0,
                    saving_percent=20.0,
                    comfort_score=94.2
                )
                await bg_opt_repo.create(opt)
                
            logger.info(f"Background simulation task completed for {sim_id}. Broacasting finalize event.")
            
            # 5. Broadcast complete over WS
            complete_event = create_websocket_event("SIMULATION_COMPLETE", {
                "progress": 100,
                "status": "finished",
                "metrics": {
                    "energy": 120.0,
                    "temperature": 22.4
                }
            })
            await ws_manager.broadcast(complete_event)
            
        except Exception as e:
            logger.error(f"Error in background simulation loop: {e}")
            error_event = create_websocket_event("SIMULATION_ERROR", {"status": "failed", "error": str(e)})
            await ws_manager.broadcast(error_event)
