from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException

from app.api.dependencies import get_ai_service
from app.ai.service import AIService
from app.schemas.common import StandardSuccessResponse

router = APIRouter()

@router.post("/analyze/{simulation_id}", response_model=StandardSuccessResponse)
async def run_ai_analysis(
    simulation_id: UUID,
    service: AIService = Depends(get_ai_service)
):
    try:
        report = await service.run_ai_optimization(simulation_id)
        return StandardSuccessResponse(
            success=True,
            data=report,
            message="LangGraph AI analysis completed successfully"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/report/{simulation_id}", response_model=StandardSuccessResponse)
async def get_ai_report(
    simulation_id: UUID,
    service: AIService = Depends(get_ai_service)
):
    decisions = await service.ai_decision_repo.get_by_simulation_id(simulation_id)
    # Find decisions generated by the LangGraph AI agent
    ai_decisions = [d for d in decisions if "LangGraph" in d.model]
    if not ai_decisions:
        raise HTTPException(
            status_code=404, 
            detail=f"No AI reports found for simulation {simulation_id}"
        )
    
    # Return the latest generated report
    latest_report = ai_decisions[0]
    return StandardSuccessResponse(
        success=True,
        data={
            "simulation_id": simulation_id,
            "final_report": latest_report.reasoning,
            "model": latest_report.model,
            "created_at": latest_report.created_at
        },
        message="AI report retrieved successfully"
    )
