"use client";

import { useAppStore } from "@/store/useAppStore";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Cpu, ThumbsUp, ThumbsDown, Thermometer, Sun } from "lucide-react";
import InfoTooltip from "@/components/dashboard/InfoTooltip";
import { cn } from "@/lib/utils";

// Helper bold text parser
function parseBoldText(text: string) {
  const parts = text.split(/\*\*([^*]+)\*\*/g);
  return parts.map((part, i) => {
    // Every odd item is a bold match
    if (i % 2 === 1) {
      return (
        <strong key={i} className="font-bold text-zinc-900 dark:text-zinc-100">
          {part}
        </strong>
      );
    }
    return part;
  });
}

// Custom Markdown structure formatter
function renderMarkdown(text: string) {
  if (!text) return null;

  // Pre-process: split inline headers stuck together (e.g. "Report ## 1. Executive Summary" -> "Report\n## 1. Executive Summary")
  let formattedText = text.replace(/([^\n])(##?\s+\d+\.)/g, "$1\n\n$2");
  formattedText = formattedText.replace(/([^\n])(-\s+\*)/g, "$1\n$2");

  const lines = formattedText.split("\n");

  return (
    <div className="space-y-2.5 max-h-[220px] overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-zinc-200 scrollbar-track-transparent">
      {lines.map((line, idx) => {
        const trimmed = line.trim();
        if (!trimmed) return null;

        // Check for Headings
        if (trimmed.startsWith("# ") || trimmed.startsWith("## ") || trimmed.startsWith("### ")) {
          const depth = trimmed.startsWith("# ") ? 1 : trimmed.startsWith("## ") ? 2 : 3;
          const cleanText = trimmed.replace(/^##?\s+/g, "").replace(/^###\s+/g, "");
          return (
            <h4
              key={idx}
              className={cn(
                "font-bold text-zinc-900 dark:text-zinc-100 tracking-tight",
                depth === 1 ? "text-[11px] uppercase tracking-wider text-zinc-400 font-extrabold mt-2 first:mt-0" : "text-xs mt-3 first:mt-0"
              )}
            >
              {cleanText}
            </h4>
          );
        }

        // Check for Bullet Lists
        if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
          const content = trimmed.substring(2);
          return (
            <div key={idx} className="flex gap-2 text-xs text-zinc-700 dark:text-zinc-300 ml-3 align-top leading-relaxed">
              <span className="text-zinc-400 select-none">•</span>
              <span className="font-medium">{parseBoldText(content)}</span>
            </div>
          );
        }

        // Regular paragraph
        return (
          <p key={idx} className="text-xs text-zinc-700 dark:text-zinc-350 leading-relaxed font-medium">
            {parseBoldText(trimmed)}
          </p>
        );
      })}
    </div>
  );
}

export default function AIReasoningCard() {
  const { decisions, submitFeedback } = useAppStore();

  // Get the most recent decision
  const latestDecision = decisions[0];

  return (
    <Card className="border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 shadow-sm h-full flex flex-col">
      <CardHeader className="pb-3 flex-shrink-0">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-base font-semibold flex items-center gap-2">
              <Cpu className="h-4.5 w-4.5 text-neutral-500" />
              Active AI Optimization Decision
              <InfoTooltip content="Displays the most recent control adjustment generated by the LLM reasoning agent and pushed directly back into the EnergyPlus simulator loop." />
            </CardTitle>
            <CardDescription>Most recent control recommendation and reasoning</CardDescription>
          </div>
          {latestDecision && (
            <Badge variant="outline" className="font-semibold text-zinc-500 border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900">
              Model: {latestDecision.modelName}
            </Badge>
          )}
        </div>
      </CardHeader>
      <CardContent className="flex-1 flex flex-col justify-between p-4">
        {!latestDecision ? (
          <div className="text-xs font-semibold text-neutral-400 text-center py-12">
            Waiting for live simulation data...
          </div>
        ) : (
          <div className="space-y-4 flex-1 flex flex-col justify-between">
            {/* Targets Setpoints */}
            <div className="grid grid-cols-2 gap-3">
              {/* HVAC setpoint target */}
              <div className="bg-neutral-50/50 border border-neutral-100 rounded-3xl p-4 flex items-center gap-4">
                <div className="p-3 bg-neutral-100 text-neutral-500 rounded-full">
                  <Thermometer className="h-6 w-6" />
                </div>
                <div>
                  <div className="text-[10px] font-bold text-neutral-400 uppercase tracking-wider">HVAC Target</div>
                  <div className="text-xl font-bold text-neutral-900 mt-0.5">
                    {latestDecision.hvacSetpoint.toFixed(1)}°C
                  </div>
                </div>
              </div>

              {/* Lighting target */}
              <div className="bg-neutral-50/50 border border-neutral-100 rounded-3xl p-4 flex items-center gap-4">
                <div className="p-3 bg-neutral-100 text-neutral-500 rounded-full">
                  <Sun className="h-6 w-6" />
                </div>
                <div>
                  <div className="text-[10px] font-bold text-neutral-400 uppercase tracking-wider">Lighting Target</div>
                  <div className="text-xl font-bold text-neutral-900 mt-0.5">
                    {latestDecision.lightingDim}%
                  </div>
                </div>
              </div>
            </div>

            {/* Explanation text */}
            <div className="bg-neutral-50/50 border border-neutral-100 dark:bg-zinc-900/10 dark:border-zinc-900 rounded-3xl p-5">
              <span className="text-[10px] font-bold text-neutral-400 uppercase tracking-wider block mb-2.5">Agent Rationale</span>
              {renderMarkdown(latestDecision.reason)}
            </div>

            {/* Validation review and telemetry details */}
            <div className="flex items-center justify-between border-t border-zinc-100 dark:border-zinc-900 pt-4 text-xs">
              <div className="text-zinc-450 dark:text-zinc-500 font-semibold">
                Token Count: <span className="font-mono">{latestDecision.tokensConsumed}</span> | Status: <span className="capitalize">{latestDecision.feedbackStatus}</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-muted-foreground font-semibold mr-1">Feedback:</span>
                <Button
                  size="sm"
                  variant={latestDecision.feedbackStatus === "correct" ? "default" : "outline"}
                  onClick={() => submitFeedback(latestDecision.id, "correct")}
                  className="h-8 px-3 text-xs flex items-center gap-1.5 font-medium"
                >
                  <ThumbsUp className="h-3.5 w-3.5" />
                  Correct
                </Button>
                <Button
                  size="sm"
                  variant={latestDecision.feedbackStatus === "incorrect" ? "destructive" : "outline"}
                  onClick={() => submitFeedback(latestDecision.id, "incorrect")}
                  className="h-8 px-3 text-xs flex items-center gap-1.5 font-medium"
                >
                  <ThumbsDown className="h-3.5 w-3.5" />
                  Incorrect
                </Button>
              </div>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
